# Documentation: https://roots.io/trellis/docs/local-development-setup/
wordpress_sites:
  pc.dev:
    site_hosts:
      - pc.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    site_install: true
    site_title: PodcasterWP
    admin_user: admin
    admin_password: admin
    admin_email: admin@pc.dev
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://pc.dev
      wp_siteurl: http://pc.dev/wp
      wp_env: development
      db_name: pcwpdb
      db_user: podcaster
      db_password: password
